In [17]:
import numpy as np

In [18]:
A = np.array([[1,2,3,4,5,6,7]])
B = np.array([0,1,0,0,0,1,0])

In [19]:
A


array([[1, 2, 3, 4, 5, 6, 7]])

In [20]:
B

array([0, 1, 0, 0, 0, 1, 0])

In [25]:
-1 * A * B

array([[ 0, -2,  0,  0,  0, -6,  0]])

In [24]:
np.dot(A, B.T)

array([8])